on: [push]

name: Run Test
jobs:
  test:
    runs-on: tibbotech/tidewine:latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: docker run -v ${PWD}/:/TIDEProjects/ tibbotech/tidewine /bin/sh -c "wine /home/tibbo/.wine/drive_c/Program\ Files/Tibbo/TIDE/Bin/tmake.exe \"C:\\users\\tibbo\\TIDEProjects\\.tests\\testcompile\\tblsortts.tpr\" -p \"C:\\users\\tibbo\\TIDEProjects\\.tests\\Platforms\" -r"
